<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:title" content="" />
<meta property="og:type" content="book" />








<meta name="description" content="">

<title></title>

<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>



</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li class="has-sub"><a href="index.html#preface"><span class="toc-section-number">1</span> Preface</a><ul>
<li><a href="1-1-prerequisites.html#prerequisites"><span class="toc-section-number">1.1</span> Prerequisites</a></li>
<li><a href="1-2-installing-r.html#installing-r"><span class="toc-section-number">1.2</span> Installing R</a></li>
<li><a href="1-3-installing-rstudio.html#installing-rstudio"><span class="toc-section-number">1.3</span> Installing RStudio</a></li>
<li class="has-sub"><a href="1-4-installing-r-packages-in-rstudio-.html#installing-r-packages-in-rstudio."><span class="toc-section-number">1.4</span> Installing R packages in RStudio.</a><ul>
<li><a href="1-4-installing-r-packages-in-rstudio-.html#standard-packages"><span class="toc-section-number">1.4.1</span> Standard packages</a></li>
<li><a href="1-4-installing-r-packages-in-rstudio-.html#bioconductor"><span class="toc-section-number">1.4.2</span> Bioconductor</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="2-motivation.html#motivation"><span class="toc-section-number">2</span> Motivation</a><ul>
<li><a href="2-1-variability-in-measurements.html#variability-in-measurements"><span class="toc-section-number">2.1</span> Variability in measurements</a></li>
<li><a href="2-2-summarising-your-data-can-lead-to-wrong-conclusions.html#summarising-your-data-can-lead-to-wrong-conclusions"><span class="toc-section-number">2.2</span> Summarising your data can lead to wrong conclusions</a></li>
<li><a href="2-3-ggplot2-an-r-package-for-beautiful-visualisations.html#ggplot2-an-r-package-for-beautiful-visualisations"><span class="toc-section-number">2.3</span> <em>ggplot2</em> An R package for beautiful visualisations</a></li>
</ul></li>
<li class="has-sub"><a href="3-r-fundamentals.html#r-fundamentals"><span class="toc-section-number">3</span> R Fundamentals</a><ul>
<li><a href="3-1-about-this-chapter.html#about-this-chapter"><span class="toc-section-number">3.1</span> About this chapter</a></li>
<li><a href="3-2-working-with-r.html#working-with-r"><span class="toc-section-number">3.2</span> Working with R</a></li>
<li class="has-sub"><a href="3-3-variables.html#variables"><span class="toc-section-number">3.3</span> Variables</a><ul>
<li><a href="3-3-variables.html#using-objects-and-functions"><span class="toc-section-number">3.3.1</span> Using objects and functions</a></li>
</ul></li>
<li><a href="3-4-quiz.html#quiz"><span class="toc-section-number">3.4</span> Quiz</a></li>
</ul></li>
<li class="has-sub"><a href="4-ggplot2-tour.html#ggplot2-tour"><span class="toc-section-number">4</span> <em>ggplot2</em> Tour</a><ul>
<li><a href="4-1-about-this-chapter-1.html#about-this-chapter-1"><span class="toc-section-number">4.1</span> About this chapter</a></li>
<li class="has-sub"><a href="4-2-building-a-plot-with-ggplot2.html#building-a-plot-with-ggplot2"><span class="toc-section-number">4.2</span> Building a plot with <em>ggplot2</em></a><ul>
<li><a href="4-2-building-a-plot-with-ggplot2.html#loading-the-iris-test-data"><span class="toc-section-number">4.2.1</span> Loading the iris test data</a></li>
<li><a href="4-2-building-a-plot-with-ggplot2.html#a-first-plot"><span class="toc-section-number">4.2.2</span> A first plot</a></li>
</ul></li>
<li><a href="4-3-mappings-versus-assignment.html#mappings-versus-assignment"><span class="toc-section-number">4.3</span> Mappings versus assignment</a></li>
<li><a href="4-4-quiz-1.html#quiz-1"><span class="toc-section-number">4.4</span> Quiz</a></li>
</ul></li>
<li class="has-sub"><a href="5-common-geoms.html#common-geoms"><span class="toc-section-number">5</span> Common Geoms</a><ul>
<li><a href="5-1-about-this-chapter-2.html#about-this-chapter-2"><span class="toc-section-number">5.1</span> About this chapter</a></li>
<li class="has-sub"><a href="5-2-continuous-geoms.html#continuous-geoms"><span class="toc-section-number">5.2</span> Continuous geoms</a><ul>
<li><a href="5-2-continuous-geoms.html#geom_smooth"><span class="toc-section-number">5.2.1</span> geom_smooth()</a></li>
<li><a href="5-2-continuous-geoms.html#whats-the-r2"><span class="toc-section-number">5.2.2</span> What’s the r<sup>2</sup>?</a></li>
<li><a href="5-2-continuous-geoms.html#geom_jitter"><span class="toc-section-number">5.2.3</span> geom_jitter()</a></li>
<li><a href="5-2-continuous-geoms.html#changing-opacity"><span class="toc-section-number">5.2.4</span> Changing opacity</a></li>
<li><a href="5-2-continuous-geoms.html#geom_histogram"><span class="toc-section-number">5.2.5</span> geom_histogram()</a></li>
</ul></li>
<li class="has-sub"><a href="5-3-discrete-geoms.html#discrete-geoms"><span class="toc-section-number">5.3</span> Discrete geoms</a><ul>
<li><a href="5-3-discrete-geoms.html#geom_point-and-geom_jitter"><span class="toc-section-number">5.3.1</span> geom_point() and geom_jitter()</a></li>
<li><a href="5-3-discrete-geoms.html#geom_boxplot-and-geom_violin"><span class="toc-section-number">5.3.2</span> geom_boxplot() and geom_violin()</a></li>
</ul></li>
<li><a href="5-4-quiz-2.html#quiz-2"><span class="toc-section-number">5.4</span> Quiz</a></li>
</ul></li>
<li class="has-sub"><a href="6-using-factors-to-subset-data-and-plots.html#using-factors-to-subset-data-and-plots"><span class="toc-section-number">6</span> Using Factors to Subset Data and Plots</a><ul>
<li><a href="6-1-about-this-chapter-3.html#about-this-chapter-3"><span class="toc-section-number">6.1</span> About this chapter</a></li>
<li><a href="6-2-factors.html#factors"><span class="toc-section-number">6.2</span> Factors</a></li>
<li><a href="6-3-colouring-by-factors.html#colouring-by-factors"><span class="toc-section-number">6.3</span> Colouring by factors</a></li>
<li><a href="6-4-small-multiple-plots.html#small-multiple-plots"><span class="toc-section-number">6.4</span> Small multiple plots</a></li>
<li><a href="6-5-summary-statistics.html#summary-statistics"><span class="toc-section-number">6.5</span> Summary Statistics</a></li>
<li><a href="6-6-quiz-3.html#quiz-3"><span class="toc-section-number">6.6</span> Quiz</a></li>
</ul></li>
<li class="has-sub"><a href="7-using-rmarkdown-for-reproducible-publishable-plots.html#using-rmarkdown-for-reproducible-publishable-plots"><span class="toc-section-number">7</span> Using RMarkdown for Reproducible Publishable Plots</a><ul>
<li><a href="7-1-about-this-chapter-4.html#about-this-chapter-4"><span class="toc-section-number">7.1</span> About this chapter</a></li>
<li><a href="7-2-being-lazy-is-a-virtue-work-hard-to-be-lazy-.html#being-lazy-is-a-virtue.-work-hard-to-be-lazy."><span class="toc-section-number">7.2</span> Being lazy is a virtue. Work hard to be lazy.</a></li>
<li class="has-sub"><a href="7-3-r-markdown.html#r-markdown"><span class="toc-section-number">7.3</span> R Markdown</a><ul>
<li><a href="7-3-r-markdown.html#a-new-r-markdown-document"><span class="toc-section-number">7.3.1</span> A new R Markdown document</a></li>
</ul></li>
<li><a href="7-4-quiz-4.html#quiz-4"><span class="toc-section-number">7.4</span> Quiz</a></li>
</ul></li>
<li class="has-sub"><a href="8-visual-customisation.html#visual-customisation"><span class="toc-section-number">8</span> Visual Customisation</a><ul>
<li><a href="8-1-themes.html#themes"><span class="toc-section-number">8.1</span> Themes</a></li>
<li><a href="8-2-quiz-5.html#quiz-5"><span class="toc-section-number">8.2</span> Quiz</a></li>
<li><a href="8-3-the-theme-function.html#the-theme-function"><span class="toc-section-number">8.3</span> The <code>theme()</code> function</a></li>
<li><a href="8-4-changing-the-order-of-categories-in-the-plot.html#changing-the-order-of-categories-in-the-plot"><span class="toc-section-number">8.4</span> Changing the order of categories in the plot</a></li>
<li><a href="8-5-changing-the-limits-of-a-continuous-scale.html#changing-the-limits-of-a-continuous-scale"><span class="toc-section-number">8.5</span> Changing the limits of a continuous scale</a></li>
<li><a href="8-6-quiz-6.html#quiz-6"><span class="toc-section-number">8.6</span> Quiz</a></li>
</ul></li>
<li class="has-sub"><a href="9-loading-your-own-data.html#loading-your-own-data"><span class="toc-section-number">9</span> Loading your own data</a><ul>
<li><a href="9-1-tidy-data.html#tidy-data"><span class="toc-section-number">9.1</span> Tidy data</a></li>
<li><a href="9-2-getting-your-data-into-tidy-format.html#getting-your-data-into-tidy-format"><span class="toc-section-number">9.2</span> Getting your data into tidy format</a></li>
<li><a href="9-3-loading-in-a-csv-file.html#loading-in-a-csv-file"><span class="toc-section-number">9.3</span> Loading in a CSV file</a></li>
<li class="has-sub"><a href="9-4-finding-the-file.html#finding-the-file"><span class="toc-section-number">9.4</span> Finding the file</a><ul>
<li><a href="9-4-finding-the-file.html#make-it-easy-on-yourself"><span class="toc-section-number">9.4.1</span> Make it easy on yourself</a></li>
</ul></li>
<li><a href="9-5-making-sure-the-data-types-are-correct.html#making-sure-the-data-types-are-correct"><span class="toc-section-number">9.5</span> Making sure the data types are correct</a></li>
<li><a href="9-6-quiz-7.html#quiz-7"><span class="toc-section-number">9.6</span> Quiz</a></li>
</ul></li>
<li class="has-sub"><a href="10-ggtree-a-package-for-plotting-phylogenetic-trees.html#ggtree-a-package-for-plotting-phylogenetic-trees"><span class="toc-section-number">10</span> <em>ggtree</em> a package for plotting phylogenetic trees</a><ul>
<li class="has-sub"><a href="10-1-ggtree-a-bioconductor-package-for-displaying-phylogenetic-trees.html#ggtree---a-bioconductor-package-for-displaying-phylogenetic-trees"><span class="toc-section-number">10.1</span> <code>ggtree</code> - a Bioconductor package for displaying phylogenetic trees</a><ul>
<li><a href="10-1-ggtree-a-bioconductor-package-for-displaying-phylogenetic-trees.html#labels"><span class="toc-section-number">10.1.1</span> Labels</a></li>
<li><a href="10-1-ggtree-a-bioconductor-package-for-displaying-phylogenetic-trees.html#annotating-and-colouring-clades"><span class="toc-section-number">10.1.2</span> Annotating and colouring clades</a></li>
</ul></li>
<li><a href="10-2-quiz-8.html#quiz-8"><span class="toc-section-number">10.2</span> Quiz</a></li>
</ul></li>
<li class="has-sub"><a href="11-using-the-stats-functions-in-r.html#using-the-stats-functions-in-r"><span class="toc-section-number">11</span> Using the stats functions in R</a><ul>
<li><a href="11-1-about-this-chapter-5.html#about-this-chapter-5"><span class="toc-section-number">11.1</span> About this chapter</a></li>
<li><a href="11-2-summary-statistics-1.html#summary-statistics-1"><span class="toc-section-number">11.2</span> Summary Statistics</a></li>
<li class="has-sub"><a href="11-3-the-independent-t-test.html#the-independent-t-test"><span class="toc-section-number">11.3</span> The independent <em>t</em> test</a><ul>
<li><a href="11-3-the-independent-t-test.html#effect-size-for-a-t-test."><span class="toc-section-number">11.3.1</span> Effect size for a <em>t</em> test.</a></li>
</ul></li>
<li><a href="11-4-linear-regression.html#linear-regression"><span class="toc-section-number">11.4</span> Linear regression</a></li>
<li><a href="11-5-one-way-anova.html#one-way-anova"><span class="toc-section-number">11.5</span> One Way ANOVA</a></li>
<li><a href="11-6-quiz-9.html#quiz-9"><span class="toc-section-number">11.6</span> Quiz</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="continuous-geoms" class="section level2">
<h2><span class="header-section-number">5.2</span> Continuous geoms</h2>
<p>Let’s look at some geoms that use continuous data on the x and y axis.</p>
<div id="geom_smooth" class="section level3">
<h3><span class="header-section-number">5.2.1</span> geom_smooth()</h3>
<p>The built in geom <code>geom_smooth()</code> is a great one for getting a nice summary line through the data</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(iris) +<span class="st"> </span><span class="kw">aes</span>(Petal.Width,Petal.Length) +<span class="st"> </span><span class="kw">geom_point</span>()
p +<span class="st"> </span><span class="kw">geom_smooth</span>()</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-26-1.png" width="672"  /> By default, this isn’t a simple line of best fit, as you can see the smoothed line has curves! And it has a grey region that shows the standard error of the line. To get the standard line of the form <code>y=mx+c</code>, use</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p +<span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-27-1.png" width="672"  /></p>
</div>
<div id="whats-the-r2" class="section level3">
<h3><span class="header-section-number">5.2.2</span> What’s the r<sup>2</sup>?</h3>
<p>Having shown you how to put the line of best fit on the graph, you probably want to know how to get the equation and r<sup>2</sup> value. That takes a little bit of pure R. Here’s how, using the <code>lm</code> linear model function. The syntax for this is <code>lm(y ~ x, dataset)</code> so for the iris data and the graph we just made (note the order Y and X is used in not the order X and Y)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>(Petal.Length ~<span class="st"> </span>Petal.Width, iris)</code></pre></div>
<p>The result is now saved in the <code>model</code> variable we just created. This is a complex R object, which we can see a summary of using</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Petal.Length ~ Petal.Width, data = iris)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.33542 -0.30347 -0.02955  0.25776  1.39453 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.08356    0.07297   14.85   &lt;2e-16 ***
## Petal.Width  2.22994    0.05140   43.39   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4782 on 148 degrees of freedom
## Multiple R-squared:  0.9271, Adjusted R-squared:  0.9266 
## F-statistic:  1882 on 1 and 148 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This is complex, but we want model coefficients, that is the <code>m</code> value - the slope (here 2.22994) and the <code>c</code> value - the intercept (here 1.08356), and the adjusted R-squared (0.9266)</p>
<blockquote>
<h2 id="shorthand-notation"><span class="header-section-number">5.2.2</span> Shorthand notation</h2>
<p>A shorthand in ggplot allows you to leave out the <code>data=</code> part of the function call, if you put the data in the first position so</p>
<p><code>ggplot(iris)</code> is the same as <code>ggplot(data=iris)</code></p>
<p>In the <code>aes()</code> function we can do the same. We can leave out the <code>x=</code> and <code>y=</code> parts and instead use the first two things in the function call for the x and y axis.</p>
<p>So <code>aes(Petal.Length, Petal.Width)</code> is the same as <code>aes(x=Petal.Length, y=Petal.Width)</code></p>
</blockquote>
</div>
<div id="geom_jitter" class="section level3">
<h3><span class="header-section-number">5.2.3</span> geom_jitter()</h3>
<p>Sometimes, point plots get crowded, the points can get too close together, a visual problem called overplotting. A jitter plot lets us get over this by adding a random bit of noise to the position of the points. Here the points from the jitter geom are set to red.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p +<span class="st"> </span><span class="kw">geom_point</span>() +<span class="st"> </span><span class="kw">geom_jitter</span>(<span class="dt">colour=</span><span class="st">&quot;Red&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-30-1.png" width="672"  /></p>
<p>We can fiddle with the range of the jitter with <code>width</code> and <code>height</code> options</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p +<span class="st"> </span><span class="kw">geom_point</span>() +<span class="st"> </span><span class="kw">geom_jitter</span>(<span class="dt">colour=</span><span class="st">&quot;Red&quot;</span>, <span class="dt">width=</span><span class="fl">0.001</span>, <span class="dt">height=</span><span class="fl">0.001</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-31-1.png" width="672"  /></p>
<p>conversely,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p +<span class="st"> </span><span class="kw">geom_point</span>() +<span class="st"> </span><span class="kw">geom_jitter</span>(<span class="dt">colour=</span><span class="st">&quot;Red&quot;</span>, <span class="dt">width=</span><span class="dv">10</span>, <span class="dt">height=</span><span class="dv">10</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-32-1.png" width="672"  /></p>
<p>The defaults are usually a good choice though.</p>
</div>
<div id="changing-opacity" class="section level3">
<h3><span class="header-section-number">5.2.4</span> Changing opacity</h3>
<p>Overplotting can be dealt with in other ways, changing the opacity of the geom is another. This is the <code>alpha</code> option. Choose the value in the range <code>0</code> to <code>1</code>, where <code>0</code> is invisible and <code>1</code> is solid</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p +<span class="st"> </span><span class="kw">geom_point</span>() +<span class="st"> </span><span class="kw">geom_jitter</span>(<span class="dt">alpha=</span><span class="fl">0.5</span>) </code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-33-1.png" width="672"  /></p>
</div>
<div id="geom_histogram" class="section level3">
<h3><span class="header-section-number">5.2.5</span> geom_histogram()</h3>
<p>Plotting a histogram is done with the <code>geom_histogram()</code>. The y value for this is calculated automatically, so you provide the x value.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(iris) +<span class="st"> </span><span class="kw">aes</span>(Petal.Width)
p +<span class="st"> </span><span class="kw">geom_histogram</span>() </code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-34-1.png" width="672"  /></p>
<p>You can change the width of the bins with <code>binwidth</code>, or set the number of bins with <code>bins</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p +<span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth=</span><span class="fl">0.5</span>) </code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-35-1.png" width="672"  /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p +<span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">5</span>) </code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-35-2.png" width="672"  /></p>
<p>Trying to map the species to colour in this one gives us a weird sort of stacked histogram.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p +<span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">5</span>, <span class="kw">aes</span>(<span class="dt">colour=</span>Species, <span class="dt">fill=</span>Species),<span class="dt">alpha=</span><span class="fl">0.3</span> ) </code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-36-1.png" width="672"  /></p>
<p>We can avoid this in a few ways, one is by using <code>geom_freqpoly()</code>, which is a line graph joining the tops of the bars of the histogram.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p +<span class="st"> </span><span class="kw">geom_freqpoly</span>( <span class="kw">aes</span>(<span class="dt">colour=</span>Species), <span class="dt">bins=</span><span class="dv">5</span> )</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-37-1.png" width="672"  /></p>
<p>or with <code>geom_density()</code> which gives us smoothed lines from a kernel density estimate of the data (which is a way of generating a smooth curve over histograms).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p +<span class="st"> </span><span class="kw">geom_density</span>( <span class="kw">aes</span>(<span class="dt">colour=</span>Species, <span class="dt">fill=</span>Species), <span class="dt">alpha=</span><span class="fl">0.3</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-38-1.png" width="672"  /></p>
</div>
</div>
<p style="text-align: center;">
<a href="5-1-about-this-chapter-2.html"><button class="btn btn-default">Previous</button></a>
<a href="5-3-discrete-geoms.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>



</body>
</html>
