project:
  type: book
  output-dir: docs

book:
  title: "Using ggplot2 to produce meaningful plots "
  author: "Dan MacLean"
  date: "May 2022"
  search: true
  downloads: [pdf]
  sharing: [twitter, facebook]
  chapters: 
    - index.qmd
    - part: "ggplot2 fundamentals"
      chapters:
        - 03-ggplot2-tour.qmd
    - part: "Making a data appropriate plot"
      chapters:
        - 04-geoms.qmd
        - 05-factors_facets.qmd
        - 07-themes.qmd
    - part: "Working reproducibly"
      chapters:
        - 06-rmarkdown.qmd
        - 08-data-loading.qmd
  appendices:
    - prerequisites.qmd
    - r-fundamentals.qmd
    - acknowledgements.qmd

format:
  html:
    theme: cosmo
    other-links:
      - text: Data Exploration and Visualisation Chatbot
        href: https://tsl-bioinformatics.shinyapps.io/datavixexp_chatbot/
        target: _blank

  pdf:
    documentclass: scrreprt
comments:
  hypothesis: true
