<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="">
  <meta name="generator" content="bookdown 0.1 and GitBook 2.6.7">

  <meta property="og:title" content="" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="ggtree-a-package-for-plotting-phylogenetic-trees.html">


<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#prerequisites"><i class="fa fa-check"></i><b>1.1</b> Prerequisites</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#installing-r"><i class="fa fa-check"></i><b>1.2</b> Installing R</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#installing-rstudio"><i class="fa fa-check"></i><b>1.3</b> Installing RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#installing-r-packages-in-rstudio."><i class="fa fa-check"></i><b>1.4</b> Installing R packages in RStudio.</a><ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#standard-packages"><i class="fa fa-check"></i><b>1.4.1</b> Standard packages</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#bioconductor"><i class="fa fa-check"></i><b>1.4.2</b> Bioconductor</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="motivation.html"><a href="motivation.html"><i class="fa fa-check"></i><b>2</b> Motivation</a><ul>
<li class="chapter" data-level="2.1" data-path="motivation.html"><a href="motivation.html#variability-in-measurements"><i class="fa fa-check"></i><b>2.1</b> Variability in measurements</a></li>
<li class="chapter" data-level="2.2" data-path="motivation.html"><a href="motivation.html#summarising-your-data-can-lead-to-wrong-conclusions"><i class="fa fa-check"></i><b>2.2</b> Summarising your data can lead to wrong conclusions</a></li>
<li class="chapter" data-level="2.3" data-path="motivation.html"><a href="motivation.html#ggplot2-an-r-package-for-beautiful-visualisations"><i class="fa fa-check"></i><b>2.3</b> <em>ggplot2</em> An R package for beautiful visualisations</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="r-fundamentals.html"><a href="r-fundamentals.html"><i class="fa fa-check"></i><b>3</b> R Fundamentals</a><ul>
<li class="chapter" data-level="3.1" data-path="r-fundamentals.html"><a href="r-fundamentals.html#about-this-chapter"><i class="fa fa-check"></i><b>3.1</b> About this chapter</a></li>
<li class="chapter" data-level="3.2" data-path="r-fundamentals.html"><a href="r-fundamentals.html#working-with-r"><i class="fa fa-check"></i><b>3.2</b> Working with R</a></li>
<li class="chapter" data-level="3.3" data-path="r-fundamentals.html"><a href="r-fundamentals.html#variables"><i class="fa fa-check"></i><b>3.3</b> Variables</a><ul>
<li class="chapter" data-level="3.3.1" data-path="r-fundamentals.html"><a href="r-fundamentals.html#using-objects-and-functions"><i class="fa fa-check"></i><b>3.3.1</b> Using objects and functions</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="r-fundamentals.html"><a href="r-fundamentals.html#quiz"><i class="fa fa-check"></i><b>3.4</b> Quiz</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ggplot2-tour.html"><a href="ggplot2-tour.html"><i class="fa fa-check"></i><b>4</b> <em>ggplot2</em> Tour</a><ul>
<li class="chapter" data-level="4.1" data-path="ggplot2-tour.html"><a href="ggplot2-tour.html#about-this-chapter-1"><i class="fa fa-check"></i><b>4.1</b> About this chapter</a></li>
<li class="chapter" data-level="4.2" data-path="ggplot2-tour.html"><a href="ggplot2-tour.html#building-a-plot-with-ggplot2"><i class="fa fa-check"></i><b>4.2</b> Building a plot with <em>ggplot2</em></a><ul>
<li class="chapter" data-level="4.2.1" data-path="ggplot2-tour.html"><a href="ggplot2-tour.html#loading-the-iris-test-data"><i class="fa fa-check"></i><b>4.2.1</b> Loading the iris test data</a></li>
<li class="chapter" data-level="4.2.2" data-path="ggplot2-tour.html"><a href="ggplot2-tour.html#a-first-plot"><i class="fa fa-check"></i><b>4.2.2</b> A first plot</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="ggplot2-tour.html"><a href="ggplot2-tour.html#mappings-versus-assignment"><i class="fa fa-check"></i><b>4.3</b> Mappings versus assignment</a></li>
<li class="chapter" data-level="4.4" data-path="ggplot2-tour.html"><a href="ggplot2-tour.html#quiz-1"><i class="fa fa-check"></i><b>4.4</b> Quiz</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="common-geoms.html"><a href="common-geoms.html"><i class="fa fa-check"></i><b>5</b> Common Geoms</a><ul>
<li class="chapter" data-level="5.1" data-path="common-geoms.html"><a href="common-geoms.html#about-this-chapter-2"><i class="fa fa-check"></i><b>5.1</b> About this chapter</a></li>
<li class="chapter" data-level="5.2" data-path="common-geoms.html"><a href="common-geoms.html#continuous-geoms"><i class="fa fa-check"></i><b>5.2</b> Continuous geoms</a><ul>
<li class="chapter" data-level="5.2.1" data-path="common-geoms.html"><a href="common-geoms.html#geom_smooth"><i class="fa fa-check"></i><b>5.2.1</b> geom_smooth()</a></li>
<li class="chapter" data-level="5.2.2" data-path="common-geoms.html"><a href="common-geoms.html#whats-the-r2"><i class="fa fa-check"></i><b>5.2.2</b> What’s the r<sup>2</sup>?</a></li>
<li class="chapter" data-level="5.2.3" data-path="common-geoms.html"><a href="common-geoms.html#geom_jitter"><i class="fa fa-check"></i><b>5.2.3</b> geom_jitter()</a></li>
<li class="chapter" data-level="5.2.4" data-path="common-geoms.html"><a href="common-geoms.html#changing-opacity"><i class="fa fa-check"></i><b>5.2.4</b> Changing opacity</a></li>
<li class="chapter" data-level="5.2.5" data-path="common-geoms.html"><a href="common-geoms.html#geom_histogram"><i class="fa fa-check"></i><b>5.2.5</b> geom_histogram()</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="common-geoms.html"><a href="common-geoms.html#discrete-geoms"><i class="fa fa-check"></i><b>5.3</b> Discrete geoms</a><ul>
<li class="chapter" data-level="5.3.1" data-path="common-geoms.html"><a href="common-geoms.html#geom_point-and-geom_jitter"><i class="fa fa-check"></i><b>5.3.1</b> geom_point() and geom_jitter()</a></li>
<li class="chapter" data-level="5.3.2" data-path="common-geoms.html"><a href="common-geoms.html#geom_boxplot-and-geom_violin"><i class="fa fa-check"></i><b>5.3.2</b> geom_boxplot() and geom_violin()</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="common-geoms.html"><a href="common-geoms.html#quiz-2"><i class="fa fa-check"></i><b>5.4</b> Quiz</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="using-factors-to-subset-data-and-plots.html"><a href="using-factors-to-subset-data-and-plots.html"><i class="fa fa-check"></i><b>6</b> Using Factors to Subset Data and Plots</a><ul>
<li class="chapter" data-level="6.1" data-path="using-factors-to-subset-data-and-plots.html"><a href="using-factors-to-subset-data-and-plots.html#about-this-chapter-3"><i class="fa fa-check"></i><b>6.1</b> About this chapter</a></li>
<li class="chapter" data-level="6.2" data-path="using-factors-to-subset-data-and-plots.html"><a href="using-factors-to-subset-data-and-plots.html#factors"><i class="fa fa-check"></i><b>6.2</b> Factors</a></li>
<li class="chapter" data-level="6.3" data-path="using-factors-to-subset-data-and-plots.html"><a href="using-factors-to-subset-data-and-plots.html#colouring-by-factors"><i class="fa fa-check"></i><b>6.3</b> Colouring by factors</a></li>
<li class="chapter" data-level="6.4" data-path="using-factors-to-subset-data-and-plots.html"><a href="using-factors-to-subset-data-and-plots.html#small-multiple-plots"><i class="fa fa-check"></i><b>6.4</b> Small multiple plots</a></li>
<li class="chapter" data-level="6.5" data-path="using-factors-to-subset-data-and-plots.html"><a href="using-factors-to-subset-data-and-plots.html#summary-statistics"><i class="fa fa-check"></i><b>6.5</b> Summary Statistics</a></li>
<li class="chapter" data-level="6.6" data-path="using-factors-to-subset-data-and-plots.html"><a href="using-factors-to-subset-data-and-plots.html#quiz-3"><i class="fa fa-check"></i><b>6.6</b> Quiz</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="using-rmarkdown-for-reproducible-publishable-plots.html"><a href="using-rmarkdown-for-reproducible-publishable-plots.html"><i class="fa fa-check"></i><b>7</b> Using RMarkdown for Reproducible Publishable Plots</a><ul>
<li class="chapter" data-level="7.1" data-path="using-rmarkdown-for-reproducible-publishable-plots.html"><a href="using-rmarkdown-for-reproducible-publishable-plots.html#about-this-chapter-4"><i class="fa fa-check"></i><b>7.1</b> About this chapter</a></li>
<li class="chapter" data-level="7.2" data-path="using-rmarkdown-for-reproducible-publishable-plots.html"><a href="using-rmarkdown-for-reproducible-publishable-plots.html#being-lazy-is-a-virtue.-work-hard-to-be-lazy."><i class="fa fa-check"></i><b>7.2</b> Being lazy is a virtue. Work hard to be lazy.</a></li>
<li class="chapter" data-level="7.3" data-path="using-rmarkdown-for-reproducible-publishable-plots.html"><a href="using-rmarkdown-for-reproducible-publishable-plots.html#r-markdown"><i class="fa fa-check"></i><b>7.3</b> R Markdown</a><ul>
<li class="chapter" data-level="7.3.1" data-path="using-rmarkdown-for-reproducible-publishable-plots.html"><a href="using-rmarkdown-for-reproducible-publishable-plots.html#a-new-r-markdown-document"><i class="fa fa-check"></i><b>7.3.1</b> A new R Markdown document</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="using-rmarkdown-for-reproducible-publishable-plots.html"><a href="using-rmarkdown-for-reproducible-publishable-plots.html#quiz-4"><i class="fa fa-check"></i><b>7.4</b> Quiz</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="visual-customisation.html"><a href="visual-customisation.html"><i class="fa fa-check"></i><b>8</b> Visual Customisation</a><ul>
<li class="chapter" data-level="8.1" data-path="visual-customisation.html"><a href="visual-customisation.html#themes"><i class="fa fa-check"></i><b>8.1</b> Themes</a></li>
<li class="chapter" data-level="8.2" data-path="visual-customisation.html"><a href="visual-customisation.html#quiz-5"><i class="fa fa-check"></i><b>8.2</b> Quiz</a></li>
<li class="chapter" data-level="8.3" data-path="visual-customisation.html"><a href="visual-customisation.html#the-theme-function"><i class="fa fa-check"></i><b>8.3</b> The <code>theme()</code> function</a></li>
<li class="chapter" data-level="8.4" data-path="visual-customisation.html"><a href="visual-customisation.html#changing-the-order-of-categories-in-the-plot"><i class="fa fa-check"></i><b>8.4</b> Changing the order of categories in the plot</a></li>
<li class="chapter" data-level="8.5" data-path="visual-customisation.html"><a href="visual-customisation.html#changing-the-limits-of-a-continuous-scale"><i class="fa fa-check"></i><b>8.5</b> Changing the limits of a continuous scale</a></li>
<li class="chapter" data-level="8.6" data-path="visual-customisation.html"><a href="visual-customisation.html#quiz-6"><i class="fa fa-check"></i><b>8.6</b> Quiz</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="loading-your-own-data.html"><a href="loading-your-own-data.html"><i class="fa fa-check"></i><b>9</b> Loading your own data</a><ul>
<li class="chapter" data-level="9.1" data-path="loading-your-own-data.html"><a href="loading-your-own-data.html#tidy-data"><i class="fa fa-check"></i><b>9.1</b> Tidy data</a></li>
<li class="chapter" data-level="9.2" data-path="loading-your-own-data.html"><a href="loading-your-own-data.html#getting-your-data-into-tidy-format"><i class="fa fa-check"></i><b>9.2</b> Getting your data into tidy format</a></li>
<li class="chapter" data-level="9.3" data-path="loading-your-own-data.html"><a href="loading-your-own-data.html#loading-in-a-csv-file"><i class="fa fa-check"></i><b>9.3</b> Loading in a CSV file</a></li>
<li class="chapter" data-level="9.4" data-path="loading-your-own-data.html"><a href="loading-your-own-data.html#finding-the-file"><i class="fa fa-check"></i><b>9.4</b> Finding the file</a><ul>
<li class="chapter" data-level="9.4.1" data-path="loading-your-own-data.html"><a href="loading-your-own-data.html#make-it-easy-on-yourself"><i class="fa fa-check"></i><b>9.4.1</b> Make it easy on yourself</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="loading-your-own-data.html"><a href="loading-your-own-data.html#making-sure-the-data-types-are-correct"><i class="fa fa-check"></i><b>9.5</b> Making sure the data types are correct</a></li>
<li class="chapter" data-level="9.6" data-path="loading-your-own-data.html"><a href="loading-your-own-data.html#quiz-7"><i class="fa fa-check"></i><b>9.6</b> Quiz</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ggtree-a-package-for-plotting-phylogenetic-trees.html"><a href="ggtree-a-package-for-plotting-phylogenetic-trees.html"><i class="fa fa-check"></i><b>10</b> <em>ggtree</em> a package for plotting phylogenetic trees</a><ul>
<li class="chapter" data-level="10.1" data-path="ggtree-a-package-for-plotting-phylogenetic-trees.html"><a href="ggtree-a-package-for-plotting-phylogenetic-trees.html#ggtree---a-bioconductor-package-for-displaying-phylogenetic-trees"><i class="fa fa-check"></i><b>10.1</b> <code>ggtree</code> - a Bioconductor package for displaying phylogenetic trees</a><ul>
<li class="chapter" data-level="10.1.1" data-path="ggtree-a-package-for-plotting-phylogenetic-trees.html"><a href="ggtree-a-package-for-plotting-phylogenetic-trees.html#labels"><i class="fa fa-check"></i><b>10.1.1</b> Labels</a></li>
<li class="chapter" data-level="10.1.2" data-path="ggtree-a-package-for-plotting-phylogenetic-trees.html"><a href="ggtree-a-package-for-plotting-phylogenetic-trees.html#annotating-and-colouring-clades"><i class="fa fa-check"></i><b>10.1.2</b> Annotating and colouring clades</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="ggtree-a-package-for-plotting-phylogenetic-trees.html"><a href="ggtree-a-package-for-plotting-phylogenetic-trees.html#quiz-8"><i class="fa fa-check"></i><b>10.2</b> Quiz</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="using-the-stats-functions-in-r.html"><a href="using-the-stats-functions-in-r.html"><i class="fa fa-check"></i><b>11</b> Using the stats functions in R</a><ul>
<li class="chapter" data-level="11.1" data-path="using-the-stats-functions-in-r.html"><a href="using-the-stats-functions-in-r.html#about-this-chapter-5"><i class="fa fa-check"></i><b>11.1</b> About this chapter</a></li>
<li class="chapter" data-level="11.2" data-path="using-the-stats-functions-in-r.html"><a href="using-the-stats-functions-in-r.html#summary-statistics-1"><i class="fa fa-check"></i><b>11.2</b> Summary Statistics</a></li>
<li class="chapter" data-level="11.3" data-path="using-the-stats-functions-in-r.html"><a href="using-the-stats-functions-in-r.html#the-independent-t-test"><i class="fa fa-check"></i><b>11.3</b> The independent <em>t</em> test</a><ul>
<li class="chapter" data-level="11.3.1" data-path="using-the-stats-functions-in-r.html"><a href="using-the-stats-functions-in-r.html#effect-size-for-a-t-test."><i class="fa fa-check"></i><b>11.3.1</b> Effect size for a <em>t</em> test.</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="using-the-stats-functions-in-r.html"><a href="using-the-stats-functions-in-r.html#linear-regression"><i class="fa fa-check"></i><b>11.4</b> Linear regression</a></li>
<li class="chapter" data-level="11.5" data-path="using-the-stats-functions-in-r.html"><a href="using-the-stats-functions-in-r.html#one-way-anova"><i class="fa fa-check"></i><b>11.5</b> One Way ANOVA</a></li>
<li class="chapter" data-level="11.6" data-path="using-the-stats-functions-in-r.html"><a href="using-the-stats-functions-in-r.html#quiz-9"><i class="fa fa-check"></i><b>11.6</b> Quiz</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="using-the-stats-functions-in-r" class="section level1">
<h1><span class="header-section-number">11</span> Using the stats functions in R</h1>
<div id="about-this-chapter-5" class="section level2">
<h2><span class="header-section-number">11.1</span> About this chapter</h2>
<ol style="list-style-type: decimal">
<li>Questions:</li>
</ol>
<ul>
<li>How do I do some common test?</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>Objectives:</li>
</ol>
<ul>
<li>Using <code>t.test()</code> and calculating effect sizes</li>
<li>Using <code>lm()</code> for regression</li>
<li>Doing ANOVA with a linear model</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>Keypoints:</li>
</ol>
<ul>
<li>There are a range of functions for doing every statistical test in R.</li>
</ul>
<p>R is built for statistics so in this section we’ll look at some common statistics functions.</p>
<p>First just getting the summary or descriptive statistics.</p>
</div>
<div id="summary-statistics-1" class="section level2">
<h2><span class="header-section-number">11.2</span> Summary Statistics</h2>
<p>Earlier we saw that R has very many ways to get summary statistics like the mean and standard deviation from entire datasets. These ranged from the <code>summary()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> <span class="kw">summary</span>(iris)</code></pre></div>
<pre><code>##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## </code></pre>
<p>But a better way to summarise by factor is with the <code>describeBy()</code> function in the <code>psych</code> package. Note you need to use <code>$</code> notation to describe the column with the factor you want to subset with.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(psych)
<span class="kw">describeBy</span>(iris, iris$Species)</code></pre></div>
<pre><code>## $setosa
##              vars  n mean   sd median trimmed  mad min max range skew
## Sepal.Length    1 50 5.01 0.35    5.0    5.00 0.30 4.3 5.8   1.5 0.11
## Sepal.Width     2 50 3.43 0.38    3.4    3.42 0.37 2.3 4.4   2.1 0.04
## Petal.Length    3 50 1.46 0.17    1.5    1.46 0.15 1.0 1.9   0.9 0.10
## Petal.Width     4 50 0.25 0.11    0.2    0.24 0.00 0.1 0.6   0.5 1.18
## Species*        5 50 1.00 0.00    1.0    1.00 0.00 1.0 1.0   0.0  NaN
##              kurtosis   se
## Sepal.Length    -0.45 0.05
## Sepal.Width      0.60 0.05
## Petal.Length     0.65 0.02
## Petal.Width      1.26 0.01
## Species*          NaN 0.00
## 
## $versicolor
##              vars  n mean   sd median trimmed  mad min max range  skew
## Sepal.Length    1 50 5.94 0.52   5.90    5.94 0.52 4.9 7.0   2.1  0.10
## Sepal.Width     2 50 2.77 0.31   2.80    2.78 0.30 2.0 3.4   1.4 -0.34
## Petal.Length    3 50 4.26 0.47   4.35    4.29 0.52 3.0 5.1   2.1 -0.57
## Petal.Width     4 50 1.33 0.20   1.30    1.32 0.22 1.0 1.8   0.8 -0.03
## Species*        5 50 2.00 0.00   2.00    2.00 0.00 2.0 2.0   0.0   NaN
##              kurtosis   se
## Sepal.Length    -0.69 0.07
## Sepal.Width     -0.55 0.04
## Petal.Length    -0.19 0.07
## Petal.Width     -0.59 0.03
## Species*          NaN 0.00
## 
## $virginica
##              vars  n mean   sd median trimmed  mad min max range  skew
## Sepal.Length    1 50 6.59 0.64   6.50    6.57 0.59 4.9 7.9   3.0  0.11
## Sepal.Width     2 50 2.97 0.32   3.00    2.96 0.30 2.2 3.8   1.6  0.34
## Petal.Length    3 50 5.55 0.55   5.55    5.51 0.67 4.5 6.9   2.4  0.52
## Petal.Width     4 50 2.03 0.27   2.00    2.03 0.30 1.4 2.5   1.1 -0.12
## Species*        5 50 3.00 0.00   3.00    3.00 0.00 3.0 3.0   0.0   NaN
##              kurtosis   se
## Sepal.Length    -0.20 0.09
## Sepal.Width      0.38 0.05
## Petal.Length    -0.37 0.08
## Petal.Width     -0.75 0.04
## Species*          NaN 0.00
## 
## attr(,&quot;call&quot;)
## by.data.frame(data = x, INDICES = group, FUN = describe, type = type)</code></pre>
<p>With this you can get a nice, comprehensive table of summary statistics across all the numerical columns, divided by the chosen factor.</p>
<p>For combinations of factors, you can use the <code>ddply()</code> function in the <code>plyr</code> package. Here you can choose a list of factors to summarise, but you must name the output columns and the R function to use. Helpfully the R function for a mean is <code>mean()</code> and the function for standard deviation is <code>sd()</code>.</p>
<p>Here, we divide up on <code>cut</code> and <code>colour</code> using the make-a-list function <code>c()</code>, we tell <code>ddply</code> we want to <code>summarise</code> and that it should add a <code>mean</code> column using the <code>mean()</code> function and an <code>sd</code> column using the <code>sd(function)</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ddply</span>(diamonds, <span class="kw">c</span>(<span class="st">&#39;cut&#39;</span>, <span class="st">&#39;color&#39;</span>), summarise, <span class="dt">mean=</span><span class="kw">mean</span>(price), <span class="dt">sd=</span><span class="kw">sd</span>(price) )</code></pre></div>
<pre><code>##          cut color     mean       sd
## 1       Fair     D 4291.061 3286.114
## 2       Fair     E 3682.312 2976.652
## 3       Fair     F 3827.003 3223.303
## 4       Fair     G 4239.255 3609.644
## 5       Fair     H 5135.683 3886.482
## 6       Fair     I 4685.446 3730.271
## 7       Fair     J 4975.655 4050.459
## 8       Good     D 3405.382 3175.149
## 9       Good     E 3423.644 3330.702
## 10      Good     F 3495.750 3202.411
## 11      Good     G 4123.482 3702.505
## 12      Good     H 4276.255 4020.660
## 13      Good     I 5078.533 4631.702
## 14      Good     J 4574.173 3707.791
## 15 Very Good     D 3470.467 3523.753
## 16 Very Good     E 3214.652 3408.024
## 17 Very Good     F 3778.820 3786.124
## 18 Very Good     G 3872.754 3861.375
## 19 Very Good     H 4535.390 4185.798
## 20 Very Good     I 5255.880 4687.105
## 21 Very Good     J 5103.513 4135.653
## 22   Premium     D 3631.293 3711.634
## 23   Premium     E 3538.914 3794.987
## 24   Premium     F 4324.890 4012.023
## 25   Premium     G 4500.742 4356.571
## 26   Premium     H 5216.707 4466.190
## 27   Premium     I 5946.181 5053.746
## 28   Premium     J 6294.592 4788.937
## 29     Ideal     D 2629.095 3001.070
## 30     Ideal     E 2597.550 2956.007
## 31     Ideal     F 3374.939 3766.635
## 32     Ideal     G 3720.706 4006.262
## 33     Ideal     H 3889.335 4013.375
## 34     Ideal     I 4451.970 4505.150
## 35     Ideal     J 4918.186 4476.207</code></pre>
<blockquote>
<h2 id="mean-and-sd"><span class="header-section-number">11.2</span> <code>mean()</code> and <code>sd()</code></h2>
<p>R has even simpler functions for getting these values from lists of numbers, the <code>mean()</code> and <code>sd()</code> functions. These take lists of numbers, rather than whole datasets: <code>mean(c(1,2,3))</code></p>
<p><code>[1] 2</code></p>
<p>or</p>
<p><code>mean(iris$Sepal.Length)</code></p>
<p><code>[1] 5.843333</code></p>
<p>These are useful for quick calculations, but less so for real datasets since you have to apply manually to every subset that you are interested in.</p>
</blockquote>
</div>
<div id="the-independent-t-test" class="section level2">
<h2><span class="header-section-number">11.3</span> The independent <em>t</em> test</h2>
<p>Let’s look at the standard independent <em>t</em> test. This is done with the <code>t.test()</code> function. Let’s look at the <code>iris</code> built in data set.</p>
<p>The general form for a tidy dataset with factors like <code>iris</code> is <code>t.test(measured_thing ~ grouping_factor, data=dataset)</code>, so to compare Petal Widths between Species in the <code>iris</code> dataset</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(Petal.Width ~<span class="st"> </span>Species, <span class="dt">data =</span> iris)</code></pre></div>
<pre><code>## Error in t.test.formula(Petal.Width ~ Species, data = iris): grouping factor must have exactly 2 levels</code></pre>
<p>Recall that this data set has 3 levels in the Species factor. The <em>t</em> test, is built for one to one comparisons only, so we must have just two things to compare (and if you end up doing more than one <em>t</em>-test to compare lots of groups, you probably should be using ANOVA!).</p>
<p>So lets use the <code>filter()</code> function from the <code>dplyr</code> package to select our two</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
small_iris &lt;-<span class="st"> </span><span class="kw">filter</span>(iris, Species ==<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;versicolor&quot;</span>, <span class="st">&quot;setosa&quot;</span>))
<span class="kw">t.test</span>(Petal.Width ~<span class="st"> </span>Species, <span class="dt">data=</span>small_iris)</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Petal.Width by Species
## t = -23.556, df = 41.092, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.1812722 -0.9947278
## sample estimates:
##     mean in group setosa mean in group versicolor 
##                    0.264                    1.352</code></pre>
<p>The output is fairly clear, the <code>p-value</code> is significant at some number less than 0.000000000000000022 (which is a built in lower limit that is caused by R running out of decimal places).</p>
<p>The mean in each group is presented for each group, is the limits of the confidence interval of the range we would expect the true difference to fall between 95% of the time (this is not the CI of the mean of each data set!).</p>
<div id="effect-size-for-a-t-test." class="section level3">
<h3><span class="header-section-number">11.3.1</span> Effect size for a <em>t</em> test.</h3>
<p>Even though the <em>p</em> value is significant at the 95% level, we do not know whether it is a substantial difference. This is an important thing to assess too since small differences can be statistically significant simply by recording a difference many times (IE by having a large number of replicates), but small differences may not be meaningful in the real world. Effect size is one way of getting a measure of the size of the difference that is more meaningful and comparable between different experiments and answering whether the difference you’ve observed is substantive as well as significant. A responsible scientist will use both <em>p</em> and effect size for deciding whether the difference between means has any real world meaning.</p>
<p>There are loads of effect sizes, we will look at two common ones for a <em>t</em> test, Cohen’s <em>d</em> and Rosenthal’s <code>r</code>.</p>
<div id="cohens-d" class="section level4">
<h4><span class="header-section-number">11.3.1.1</span> Cohen’s <em>d</em></h4>
<p>Cohen’s <em>d</em> is a standardized measure of effect and can be thought of the number of standard deviations between the means. Different <em>d</em> mean different things:</p>
<table>
<tr>
<td>
~0.2
</td>
<td>
small effect
</td>
</tr>
<tr>
<td>
~0.5
</td>
<td>
medium effect
</td>
</tr>
<tr>
<td>
~0.8
</td>
<td>
large effect
</td>
</tr>
</table>
<p>The <em>d</em> can be calculated using the <code>cohen.d()</code> function in the <code>effsize</code> package and it works just like the <code>t.test()</code> function</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(effsize)
<span class="kw">cohen.d</span>(Petal.Width ~<span class="st"> </span>Species, <span class="dt">data=</span>small_iris)</code></pre></div>
<pre><code>## Error in cohen.d.default(d, f, ...): Factor should have only two levels</code></pre>
<p>Doing this throws an error, because of an inconsistency between the programmers of the <code>t.test()</code> function, the <code>filter()</code> function and the <code>cohen.d()</code> function. Even though we filtered our <code>iris</code> dataset to just two levels, the <code>levels</code> attribute of the <code>small_iris</code> dataset still says there are 3 levels!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">levels</span>(small_iris$Species)</code></pre></div>
<pre><code>## [1] &quot;setosa&quot;     &quot;versicolor&quot; &quot;virginica&quot;</code></pre>
<p>Which is annoying. The <code>t.test()</code> function just worked out the right number of levels, but the <code>cohen.d()</code> checks the <code>levels</code> attribute instead. This inconsistency is just a thing that happens when different people write different code. So to fix the levels after filtering we must manually set them</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">small_iris$Species &lt;-<span class="st"> </span><span class="kw">factor</span>(small_iris$Species, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;setosa&quot;</span>, <span class="st">&quot;versicolor&quot;</span>))
<span class="kw">cohen.d</span>(Petal.Width ~<span class="st"> </span>Species, <span class="dt">data=</span>small_iris)</code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: -6.662612 (large)
## 95 percent confidence interval:
##       inf       sup 
## -8.173936 -5.151289</code></pre>
<p>And <code>cohen.d()</code> tells us this is a large difference, with <em>d</em> = -6.663 (you can ignore the sign of the <em>d</em>).</p>
</div>
<div id="rosenthals-r" class="section level4">
<h4><span class="header-section-number">11.3.1.2</span> Rosenthal’s <em>r</em></h4>
<p>Another well used effect size is <em>r</em>. It is calculated with this formula, using <em>t</em> and <em>df</em> (degrees of freedom from the <code>t.test()</code>):</p>
<div class="figure">
<img src="fig/r.png" alt="R" />
<p class="caption">R</p>
</div>
<p>Different values of <em>r</em> indicate different effect sizes, here’s some rough rules.</p>
<table>
<tr>
<td>
~0.1
</td>
<td>
small effect
</td>
</tr>
<tr>
<td>
~0.3
</td>
<td>
medium effect
</td>
</tr>
<tr>
<td>
~0.5
</td>
<td>
large effect
</td>
</tr>
</table>
<p>The values for <em>t</em> and <em>df</em> can be extracted from the result of <code>t.test()</code> and the value of <code>r</code> calculated. Let’s specify a custom function to do this for us.</p>
<p>## Making a function Functions are the building blocks of R and it allows you to make your own. Its actually quite easy, its just a call to the function called <code>function()</code> and some regular R code surrounded by a couple of curly brackets - <code>{ }</code>. Here’s how we’d define our own squaring function:</p>
<p><code>my_square &lt;- function(x){ return(x * x) }</code></p>
<p>Now <code>my_square()</code> is a new function in R. We can use it like:</p>
<p><code>my_square(2)</code> <code>[1] 4</code></p>
<ul>
<li>The <code>x</code> is a temporary name for any data you want to use within the function.</li>
<li>The <code>return()</code> keyword simply tells the function what to send you back here</li>
<li>To send data into the function you simply put it in the brackets after the function name.</li>
<li>The R code in the function can be as long as you want and split over many lines</li>
</ul>
<p>Here’s a custom function for <em>r</em>,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rosenthal_r &lt;-<span class="st"> </span>function(t_test_result){
    t &lt;-<span class="st"> </span>t_test_result$statistic[[<span class="dv">1</span>]]
    df &lt;-<span class="st"> </span>t_test_result$parameter[[<span class="dv">1</span>]]
    r &lt;-<span class="st"> </span><span class="kw">sqrt</span>(t^<span class="dv">2</span>/(t^<span class="dv">2</span>+df))
    <span class="kw">return</span>(r)
}</code></pre></div>
<p>Here’s how we use it:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">my_t &lt;-<span class="st"> </span><span class="kw">t.test</span>(Petal.Width ~<span class="st"> </span>Species, <span class="dt">data=</span>small_iris)
<span class="kw">rosenthal_r</span>(my_t)</code></pre></div>
<pre><code>## [1] 0.9649093</code></pre>
<p>Functions are useful because they are reuseable and save lots of typing. The actual value of <em>r</em> we get here is 0.96, which is considered a large effect.</p>
</div>
</div>
</div>
<div id="linear-regression" class="section level2">
<h2><span class="header-section-number">11.4</span> Linear regression</h2>
<p>Linear regression (or as some think of it - correlation analysis) is at the base of a whole lot of statistics. In R it’s done with the <code>lm()</code> function. <code>lm</code> stands for ‘linear model’ as the resulting formula gives us a line in the form <code>y=mx+c</code> that describes the relationship between our input data and can be used as a model to make predictions. Doing an <code>lm()</code> is similar to the <code>t.test()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lm</span>(Petal.Width ~<span class="st"> </span>Petal.Length, <span class="dt">data=</span>iris)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Petal.Width ~ Petal.Length, data = iris)
## 
## Coefficients:
##  (Intercept)  Petal.Length  
##      -0.3631        0.4158</code></pre>
<p>Which is the minimal information we need the first number (Intercept) -0.3631 is the <code>c</code> of <code>y=mx+c</code>, the place where the axis is crossed and the other (Petal.Length, 0.4158) is the gradient of the line. But we also want the <em>p</em> and <em>R</em> values, these are obtained by using the summary function on the result of <code>lm()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">l &lt;-<span class="st"> </span><span class="kw">lm</span>(Petal.Width ~<span class="st"> </span>Petal.Length, <span class="dt">data=</span>iris)
<span class="kw">summary</span>(l)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Petal.Width ~ Petal.Length, data = iris)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.56515 -0.12358 -0.01898  0.13288  0.64272 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -0.363076   0.039762  -9.131  4.7e-16 ***
## Petal.Length  0.415755   0.009582  43.387  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2065 on 148 degrees of freedom
## Multiple R-squared:  0.9271, Adjusted R-squared:  0.9266 
## F-statistic:  1882 on 1 and 148 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Where we can see that the <em>R</em> is 0.9266 and <em>p</em> is again &lt; 2.2e-16.</p>
<p>The <code>lm()</code> function works fine for a dataset with only one factor, in this example we’ve completely ignored the fact that the <code>Petal.Length</code> and <code>Petal.Width</code> are from 3 species. If we want to do the linear model species wise, we need to filter the data first</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ve &lt;-<span class="st"> </span><span class="kw">filter</span>(iris, Species ==<span class="st"> &quot;versicolor&quot;</span>)
<span class="kw">lm</span>(Petal.Width ~<span class="st"> </span>Petal.Length, <span class="dt">data=</span>ve)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Petal.Width ~ Petal.Length, data = ve)
## 
## Coefficients:
##  (Intercept)  Petal.Length  
##     -0.08429       0.33105</code></pre>
</div>
<div id="one-way-anova" class="section level2">
<h2><span class="header-section-number">11.5</span> One Way ANOVA</h2>
<p>The ANOVA is actually based on a linear model so we need to construct that first, again with the <code>lm()</code> function. This time we use the factor we want to use to split the data up as the second variable. We do the actual ANOVA with <code>aov()</code> function and get the answers with the <code>summary.lm()</code> function on that.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">l &lt;-<span class="st"> </span><span class="kw">lm</span>(Petal.Width ~<span class="st"> </span>Species, <span class="dt">data =</span> iris)
a &lt;-<span class="st"> </span><span class="kw">aov</span>(l)
<span class="kw">summary.lm</span>(a)</code></pre></div>
<pre><code>## 
## Call:
## aov(formula = l)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -0.626 -0.126 -0.026  0.154  0.474 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        0.24600    0.02894    8.50 1.96e-14 ***
## Speciesversicolor  1.08000    0.04093   26.39  &lt; 2e-16 ***
## Speciesvirginica   1.78000    0.04093   43.49  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2047 on 147 degrees of freedom
## Multiple R-squared:  0.9289, Adjusted R-squared:  0.9279 
## F-statistic:   960 on 2 and 147 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Then we can apply Tukey’s HSD to get the actual <em>p</em>-values between groups.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">TukeyHSD</span>(a)</code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = l)
## 
## $Species
##                      diff       lwr       upr p adj
## versicolor-setosa    1.08 0.9830903 1.1769097     0
## virginica-setosa     1.78 1.6830903 1.8769097     0
## virginica-versicolor 0.70 0.6030903 0.7969097     0</code></pre>
<p>where the column <code>diff</code> gives us the difference between means, the <code>lwr</code> and <code>upr</code> bounds are the confidence interval and <code>p adj</code> is the <em>p</em> value rounded off. Here Petal Widths are significantly different between the species.</p>
</div>
<div id="quiz-9" class="section level2">
<h2><span class="header-section-number">11.6</span> Quiz</h2>
<ol style="list-style-type: decimal">
<li>Using the <code>mtcars</code> dataset, work out whether the number of cylinders (cyl) in a car has an effect on the mpg (miles per gallon), specifically answer whether any difference is statistically significant and substantial. Hints: Remember to use the <code>str()</code> function to check factors are factors. A one-way ANOVA should be appropriate for this sort of data. The <code>F</code> statistic or ratio is a good estimate of effect size. Extra Credit: Do any of the warnings about ‘unbalanced’ design make you worry about the results of the test?</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ggtree-a-package-for-plotting-phylogenetic-trees.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>


<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
